"""Fourth migration: add profile_pic_path to the schema of the database

Revision ID: 77638bc9b806
Revises: 31e31ddbb52e
Create Date: 2022-05-10 02:40:19.783662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77638bc9b806'
down_revision = '31e31ddbb52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pass_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
